# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
User.destroy_all
Spot.destroy_all
Review.destroy_all
user_1 = User.create!(:email => 'nick@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret')
user_2 = User.create!(:email => 'brianna@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret')
user_3 = User.create!(:email => 'amylynn@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret')
admin = User.create!(:email => 'ateam@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret', admin: true)

spots = [
  {name:'Tobin School Graffiti Murals',location:'40 Smith St, Boston MA',location_lat:'42.3329557',location_lng:'-71.100527',description:'Graffiti murals at Tobin School. Internationally known mural artist, Caleb Neelon, applied for spray paint and sandwich money to underwrite the transformation of a large wall for the Tobin School in Mission Hill. For those who love art and our fair city, Neelon\'s TEDx Boston presentation (\'Courting the Creative Class\') is a must watch.', remote_photo_url:'https://s3.amazonaws.com/arts-bostonia/arts-bostonia-production/tobin-school-graffiti.jpg',user:user_1, artist: 'Caleb Neelon'},

  {name:'Make Way for Ducklings Statue',location:'Boston Public Garden, Charles Street, Boston, Massachusetts',location_lat:'42.3541653',location_lng:'-71.0725965',description:'Mrs. Mallard and her brood are a beloved fixture in Boston Public Garden. In Robert McCloskeys 1941 beloved children\'s tale classic, Make Way for Ducklings, Mr. and Mrs. Mallard come to Boston when searching for the perfect home for their soon-to-be family.  They find the Public Garden, and decide to spend the night on the little island in the Lagoon.',remote_photo_url:'https://s3.amazonaws.com/arts-bostonia/arts-bostonia-production/makewayducklings.jpg',user:user_1,artist: 'Nancy Schon'},

  {name:'All Saints Way',location:'4 Battery Street, Boston, Massachusetts, 02109',location_lat:'42.3663982',location_lng:'-71.0525393',description:'"Mock all and sundry things, but leave the saints alone." Peter Baldassari has been collecting trinkets and mementos depicting the saints since he was a child. Now at 63, his collection has grown into a street side shrine, a display of the canonized including photos, statues, prayer cards, and more in an alley between 4 and 8 Battery Street in Boston’s North Side. An unimposing black door leads to the brick-walled sanctuary, displaying above it a “featured” saint, usually the newly divined. Vistors come from all over the world to see Baldassari’s holy collection, and many strangers and neighbors alike contribute to the exhibit. While the shrine is a personal project on private property, Baldassari has been known to give quick tours, and a good portion of the collection is visible from the street, even if the gate is locked.',remote_photo_url:'https://s3.amazonaws.com/arts-bostonia/arts-bostonia-production/allsaints.jpeg',user:user_1},

  {name:'Andre The Giant',location:'23 Kingston St, Boston, MA, 02111',location_lat:'42.353776',location_lng:'-71.058913',description:'An introspective into Bostonia life, only a Giant could have tagged this building. Visible from the street (and Deck 7 of Launch Academy).',remote_photo_url:'https://s3.amazonaws.com/arts-bostonia/arts-bostonia-production/IMG_4357.jpg',user:user_1},

  {name:'Site of the First Bell of Boston',location:'19 N Square, Boston, Massachusetts, 02113',location_lat:'42.363739',location_lng:'-71.0537',description:'Paul Revere continued to work as a successful businessman after the war, operating a bell foundry and copper mill. Revere’s foundry on Foster Street near the corner of Commercial Street served many local businesses and created many bells, but none so special as the first. Here he learned how to cast bells and recast a cracked bell for his own church, the Second Church, creating the first bell ever cast in Boston. Apparently it wasn’t a great first job. “The sound is not clear and prolonged, from the lips to the crown shrill.” said Reverend William Bentley. At the Paul Revere house, the courtyard has a bell and a small mortar and a copper hull pin from the USS Constitution, made by Paul Revere & Sons.',remote_photo_url:'https://s3.amazonaws.com/arts-bostonia/arts-bostonia-production/bostonbell.jpg',user:user_1},

  {name:'Potato Shed Memorial',location:'Millers River Littoral Way, Boston, Massachusetts',location_lat:'42.369697',location_lng:'-71.0642532',description:'A solid stack of sacks of potatoes, made of cast stone, looks as though it’s been wedged within a small, random slice of sidewalk off the side of a Boston Highway. A nearby plaque, featuring the words “potato” and “potatoes” in various sizes scattered across its top half, explains why. The monument memorializes the potato sheds that once stood along the river. From the mid-19th century up until they were burnt to a crisp in the 1960s, the storage sheds lining the railway lines in the Millers River Basin were stuffed full of potatoes. Over the span of their lifetimes, the sheds were temporary homes for millions of the tasty tubers.',remote_photo_url:'https://s3.amazonaws.com/arts-bostonia/arts-bostonia-production/potatoShedStatu.jpg',user:user_1},

  {name:'Salada Tea Doors',location:'330 Stuart Street, Boston, Massachusetts, 02116',location_lat:'42.34945',location_lng:'-71.0717256',description:'The history of the tea trade is told in bas-relief on this historic pair of Boston doors. These twelve-foot-tall, two-ton bronze doors were commissioned by Peter C. Larkin, founder of the Salada Tea Company, to celebrate his industry’s storied past. The doors were designed by sculptor Henry Wilson and feature ten panels telling the story of the exotic origins of tea. They depict scenes including Ceylonese famers harvesting, sorting and drying tea leaves, workers transporting tea boxes on their heads, elephants carrying tea boxes, and tea being loaded onto ships. The outer doorframe, carved by artist Caesar Caira, includes pilasters of stylized Asian women, a frieze featuring elephants, and high-relief statues of Demeter, goddess of the harvest, with her children. In 1927, the doors won a silver medal at the Paris Salon for their exquisite craftsmenship.',remote_photo_url:'https://s3.amazonaws.com/arts-bostonia/arts-bostonia-production/saladateadoors.jpeg',user:user_1, artist:'Henry Wilson'},

  {name:'Memorial for Boston Light Keepers',location:'49 Snow Hill St, Copp\'s Hill Cemetery, Boston, Massachusetts, 02113',location_lat:'42.3672563',location_lng:'-71.0559509',description:'Tragedy on Little Brewster Island memorialized.This triple headstone can be found near the center of the cemetery, and serves as a memorial to this strange and tragic week in Boston Light\'s history. The first lighthouse established in America was on Little Brewster Island in Boston Harbor and was first lit on September 14, 1716.  A tonnage tax of 1 penny per ton on all vessels, except coasters, moving in or out of Boston Harbor, paid for maintaining the light.  The first keeper, George Worthylake, with a salary of $50 a year, also acted as pilot for vessels entering the harbor.  In 1718 he and his wife and daughter, with two men, were drowned when the lighthouse boat capsized as they were returning to the island from Boston.  Young Benjamin Franklin, then a printer in Boston, wrote a ballad about the incident entitled "Lighthouse Tragedy" and sold it on the streets of Boston',remote_photo_url:'https://s3.amazonaws.com/arts-bostonia/arts-bostonia-production/lightkeepermemorial.png',user:user_1},

  {name:'Monument to Ether',location:'8 Arlington St, Boston Public Garden, MA, 02116',location_lat:'42.3541653',location_lng:'-71.0725965',description:'The Ether Monument is the oldest monument in the Boston Public Garden, installed in 1868. This forty-foot-tall monument commemorates a medical breakthrough: the use of ether as an anesthetic, a pivotal moment in medical history. The first public demonstration of ether anesthesia was conducted at Massachusetts General Hospital in 1846 by Boston dentist William Thomas Green Morton and Doctor John Collins Warren. Morton administered the ether, and Warren then removed a tumor from an unconscious patient. Atop the Ether monument, two figures sculpted by John Quincy Adams Ward enact a famous Biblical story about the relief of suffering: the Good Samaritan caring for an injured stranger he met on the road.',remote_photo_url:'https://s3.amazonaws.com/arts-bostonia/arts-bostonia-production/EtherMonument.jpg',user:user_1},

  {name:'Edgar Allan Poe Square',location:'176 Boylston St, Boston, MA 02116',location_lat:'42.3522424',location_lng:'-71.069283',description:'The house where Edgar Allan Poe was born on January 19, 1809, no longer exists. Neither does the street on which the house stood, since the whole area was demolished during an urban renewal project many decades ago. However, in 2009 on the 200th anniversary of Poe’s birth, Boston renamed the small plaza across the street from the southwest corner the “Common Edgar Allan Poe Square” and installed a street sign according. The plaza is near the theater district at the intersection of Boylston and Charles Streets, close to where Poe’s house once stood.',remote_photo_url:'https://s3.amazonaws.com/arts-bostonia/arts-bostonia-production/rocknakpoepfo1.jpg',user:user_1,artist: "Stefanie Rocknak"}
]
spots.each do |item|
  spot = Spot.create!(item)
end
user_1 = User.last
spot_1 = Spot.last
Review.create!(description: "Some amazing place!", rating: 5, spot: spot_1, user: user_1)
